// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcACkUqackMDPwxya6Q323V0rZ5tG_ceY',
    appId: '1:1011305826733:web:59fcc63202f840cd88f924',
    messagingSenderId: '1011305826733',
    projectId: 'my-notes-elchin',
    authDomain: 'my-notes-elchin.firebaseapp.com',
    storageBucket: 'my-notes-elchin.appspot.com',
    measurementId: 'G-0R3HN788NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfQ2vj_87UChUF1YkTKHu-kl-DEYLiX78',
    appId: '1:1011305826733:android:2b86a310d0c03ea288f924',
    messagingSenderId: '1011305826733',
    projectId: 'my-notes-elchin',
    storageBucket: 'my-notes-elchin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDY3okGAxNUoBbpcBQXbE8c8xMDdEPAZg',
    appId: '1:1011305826733:ios:abc290cbcb1b6a9088f924',
    messagingSenderId: '1011305826733',
    projectId: 'my-notes-elchin',
    storageBucket: 'my-notes-elchin.appspot.com',
    iosBundleId: 'com.elchin.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDY3okGAxNUoBbpcBQXbE8c8xMDdEPAZg',
    appId: '1:1011305826733:ios:c915edcad4cce3f588f924',
    messagingSenderId: '1011305826733',
    projectId: 'my-notes-elchin',
    storageBucket: 'my-notes-elchin.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcACkUqackMDPwxya6Q323V0rZ5tG_ceY',
    appId: '1:1011305826733:web:f36743800f56735a88f924',
    messagingSenderId: '1011305826733',
    projectId: 'my-notes-elchin',
    authDomain: 'my-notes-elchin.firebaseapp.com',
    storageBucket: 'my-notes-elchin.appspot.com',
    measurementId: 'G-F4CFVG0VSJ',
  );
}
